### Health
GET http://localhost:3000/

### Create Post
POST http://localhost:3000/post
Content-Type: application/json

{
  "senderId": "u123",
  "title": "Hello",
  "content": "My first post"
}

### Get All Posts
GET http://localhost:3000/post

### Get Posts by Sender
GET http://localhost:3000/post?sender=u123

### Get Post by ID (paste from Create Post response)
GET http://localhost:3000/post/<POST_ID>

### Get All Comments For Specific Post
GET http://localhost:3000/post/<POST_ID>/comments

### Update Post
PUT http://localhost:3000/post/<POST_ID>
Content-Type: application/json

{
  "senderId": "u123",
  "title": "Hello updated",
  "content": "Updated content"
}

### Create Comment
POST http://localhost:3000/comments
Content-Type: application/json

{
  "postId": "<POST_ID>",
  "senderId": "u777",
  "message": "Nice post!"
}

### Get All Comments
GET http://localhost:3000/comments

### Get Comment By ID
GET http://localhost:3000/comments/<COMMENT_ID>

### Update Comment
PUT http://localhost:3000/comments/<COMMENT_ID>
Content-Type: application/json

{
  "postId": "<POST_ID>",
  "senderId": "u777",
  "message": "Updated comment text"
}

### Delete Comment
DELETE http://localhost:3000/comments/<COMMENT_ID>